# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michaelbarakat/projects/mighty-core

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michaelbarakat/projects/mighty-core

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.10.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelbarakat/projects/mighty-core/CMakeFiles /Users/michaelbarakat/projects/mighty-core//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelbarakat/projects/mighty-core/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mighty-core

# Build rule for target.
mighty-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mighty-core
.PHONY : mighty-core

# fast build rule for target.
mighty-core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/build
.PHONY : mighty-core/fast

#=============================================================================
# Target rules for targets named imgui_lib

# Build rule for target.
imgui_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui_lib
.PHONY : imgui_lib

# fast build rule for target.
imgui_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/build
.PHONY : imgui_lib/fast

#=============================================================================
# Target rules for targets named mighty-core-host-check

# Build rule for target.
mighty-core-host-check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mighty-core-host-check
.PHONY : mighty-core-host-check

# fast build rule for target.
mighty-core-host-check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-host-check.dir/build.make CMakeFiles/mighty-core-host-check.dir/build
.PHONY : mighty-core-host-check/fast

#=============================================================================
# Target rules for targets named mighty-core-ui

# Build rule for target.
mighty-core-ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mighty-core-ui
.PHONY : mighty-core-ui

# fast build rule for target.
mighty-core-ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/build
.PHONY : mighty-core-ui/fast

#=============================================================================
# Target rules for targets named mighty-core-synth-host

# Build rule for target.
mighty-core-synth-host: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mighty-core-synth-host
.PHONY : mighty-core-synth-host

# fast build rule for target.
mighty-core-synth-host/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-synth-host.dir/build.make CMakeFiles/mighty-core-synth-host.dir/build
.PHONY : mighty-core-synth-host/fast

#=============================================================================
# Target rules for targets named DaisySP

# Build rule for target.
DaisySP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DaisySP
.PHONY : DaisySP

# fast build rule for target.
DaisySP/fast:
	$(MAKE) $(MAKESILENT) -f _deps/daisysp-build/CMakeFiles/DaisySP.dir/build.make _deps/daisysp-build/CMakeFiles/DaisySP.dir/build
.PHONY : DaisySP/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/CMakeFiles/uninstall.dir/build.make _deps/glfw-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build.make _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named mmc-tests

# Build rule for target.
mmc-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmc-tests
.PHONY : mmc-tests

# fast build rule for target.
mmc-tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/mmc-tests.dir/build.make tests/CMakeFiles/mmc-tests.dir/build
.PHONY : mmc-tests/fast

_deps/imgui-src/backends/imgui_impl_glfw.o: _deps/imgui-src/backends/imgui_impl_glfw.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.o

_deps/imgui-src/backends/imgui_impl_glfw.i: _deps/imgui-src/backends/imgui_impl_glfw.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.i

_deps/imgui-src/backends/imgui_impl_glfw.s: _deps/imgui-src/backends/imgui_impl_glfw.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_glfw.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_glfw.cpp.s

_deps/imgui-src/backends/imgui_impl_opengl3.o: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.o

# target to build an object file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.o
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.o

_deps/imgui-src/backends/imgui_impl_opengl3.i: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.i

# target to preprocess a source file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.i
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.i

_deps/imgui-src/backends/imgui_impl_opengl3.s: _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/backends/imgui_impl_opengl3.cpp.s
.PHONY : _deps/imgui-src/backends/imgui_impl_opengl3.cpp.s

_deps/imgui-src/imgui.o: _deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.o

# target to build an object file
_deps/imgui-src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui.cpp.o
.PHONY : _deps/imgui-src/imgui.cpp.o

_deps/imgui-src/imgui.i: _deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.i

# target to preprocess a source file
_deps/imgui-src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui.cpp.i
.PHONY : _deps/imgui-src/imgui.cpp.i

_deps/imgui-src/imgui.s: _deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.s

# target to generate assembly for a file
_deps/imgui-src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui.cpp.s
.PHONY : _deps/imgui-src/imgui.cpp.s

_deps/imgui-src/imgui_draw.o: _deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.o

# target to build an object file
_deps/imgui-src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_draw.cpp.o
.PHONY : _deps/imgui-src/imgui_draw.cpp.o

_deps/imgui-src/imgui_draw.i: _deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.i

# target to preprocess a source file
_deps/imgui-src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_draw.cpp.i
.PHONY : _deps/imgui-src/imgui_draw.cpp.i

_deps/imgui-src/imgui_draw.s: _deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.s

# target to generate assembly for a file
_deps/imgui-src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_draw.cpp.s
.PHONY : _deps/imgui-src/imgui_draw.cpp.s

_deps/imgui-src/imgui_tables.o: _deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.o

# target to build an object file
_deps/imgui-src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_tables.cpp.o
.PHONY : _deps/imgui-src/imgui_tables.cpp.o

_deps/imgui-src/imgui_tables.i: _deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.i

# target to preprocess a source file
_deps/imgui-src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_tables.cpp.i
.PHONY : _deps/imgui-src/imgui_tables.cpp.i

_deps/imgui-src/imgui_tables.s: _deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.s

# target to generate assembly for a file
_deps/imgui-src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_tables.cpp.s
.PHONY : _deps/imgui-src/imgui_tables.cpp.s

_deps/imgui-src/imgui_widgets.o: _deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.o

# target to build an object file
_deps/imgui-src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_widgets.cpp.o
.PHONY : _deps/imgui-src/imgui_widgets.cpp.o

_deps/imgui-src/imgui_widgets.i: _deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.i

# target to preprocess a source file
_deps/imgui-src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_widgets.cpp.i
.PHONY : _deps/imgui-src/imgui_widgets.cpp.i

_deps/imgui-src/imgui_widgets.s: _deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.s

# target to generate assembly for a file
_deps/imgui-src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui_lib.dir/build.make CMakeFiles/imgui_lib.dir/_deps/imgui-src/imgui_widgets.cpp.s
.PHONY : _deps/imgui-src/imgui_widgets.cpp.s

host/main.o: host/main.cpp.o
.PHONY : host/main.o

# target to build an object file
host/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-host-check.dir/build.make CMakeFiles/mighty-core-host-check.dir/host/main.cpp.o
.PHONY : host/main.cpp.o

host/main.i: host/main.cpp.i
.PHONY : host/main.i

# target to preprocess a source file
host/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-host-check.dir/build.make CMakeFiles/mighty-core-host-check.dir/host/main.cpp.i
.PHONY : host/main.cpp.i

host/main.s: host/main.cpp.s
.PHONY : host/main.s

# target to generate assembly for a file
host/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-host-check.dir/build.make CMakeFiles/mighty-core-host-check.dir/host/main.cpp.s
.PHONY : host/main.cpp.s

host/synth_host.o: host/synth_host.cpp.o
.PHONY : host/synth_host.o

# target to build an object file
host/synth_host.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-synth-host.dir/build.make CMakeFiles/mighty-core-synth-host.dir/host/synth_host.cpp.o
.PHONY : host/synth_host.cpp.o

host/synth_host.i: host/synth_host.cpp.i
.PHONY : host/synth_host.i

# target to preprocess a source file
host/synth_host.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-synth-host.dir/build.make CMakeFiles/mighty-core-synth-host.dir/host/synth_host.cpp.i
.PHONY : host/synth_host.cpp.i

host/synth_host.s: host/synth_host.cpp.s
.PHONY : host/synth_host.s

# target to generate assembly for a file
host/synth_host.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-synth-host.dir/build.make CMakeFiles/mighty-core-synth-host.dir/host/synth_host.cpp.s
.PHONY : host/synth_host.cpp.s

host/ui_host.o: host/ui_host.cpp.o
.PHONY : host/ui_host.o

# target to build an object file
host/ui_host.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/host/ui_host.cpp.o
.PHONY : host/ui_host.cpp.o

host/ui_host.i: host/ui_host.cpp.i
.PHONY : host/ui_host.i

# target to preprocess a source file
host/ui_host.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/host/ui_host.cpp.i
.PHONY : host/ui_host.cpp.i

host/ui_host.s: host/ui_host.cpp.s
.PHONY : host/ui_host.s

# target to generate assembly for a file
host/ui_host.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/host/ui_host.cpp.s
.PHONY : host/ui_host.cpp.s

host/wav_reader.o: host/wav_reader.cpp.o
.PHONY : host/wav_reader.o

# target to build an object file
host/wav_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/host/wav_reader.cpp.o
.PHONY : host/wav_reader.cpp.o

host/wav_reader.i: host/wav_reader.cpp.i
.PHONY : host/wav_reader.i

# target to preprocess a source file
host/wav_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/host/wav_reader.cpp.i
.PHONY : host/wav_reader.cpp.i

host/wav_reader.s: host/wav_reader.cpp.s
.PHONY : host/wav_reader.s

# target to generate assembly for a file
host/wav_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core-ui.dir/build.make CMakeFiles/mighty-core-ui.dir/host/wav_reader.cpp.s
.PHONY : host/wav_reader.cpp.s

src/core/MightyMusicCore.o: src/core/MightyMusicCore.cpp.o
.PHONY : src/core/MightyMusicCore.o

# target to build an object file
src/core/MightyMusicCore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/core/MightyMusicCore.cpp.o
.PHONY : src/core/MightyMusicCore.cpp.o

src/core/MightyMusicCore.i: src/core/MightyMusicCore.cpp.i
.PHONY : src/core/MightyMusicCore.i

# target to preprocess a source file
src/core/MightyMusicCore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/core/MightyMusicCore.cpp.i
.PHONY : src/core/MightyMusicCore.cpp.i

src/core/MightyMusicCore.s: src/core/MightyMusicCore.cpp.s
.PHONY : src/core/MightyMusicCore.s

# target to generate assembly for a file
src/core/MightyMusicCore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/core/MightyMusicCore.cpp.s
.PHONY : src/core/MightyMusicCore.cpp.s

src/engine/Input.o: src/engine/Input.cpp.o
.PHONY : src/engine/Input.o

# target to build an object file
src/engine/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Input.cpp.o
.PHONY : src/engine/Input.cpp.o

src/engine/Input.i: src/engine/Input.cpp.i
.PHONY : src/engine/Input.i

# target to preprocess a source file
src/engine/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Input.cpp.i
.PHONY : src/engine/Input.cpp.i

src/engine/Input.s: src/engine/Input.cpp.s
.PHONY : src/engine/Input.s

# target to generate assembly for a file
src/engine/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Input.cpp.s
.PHONY : src/engine/Input.cpp.s

src/engine/Output.o: src/engine/Output.cpp.o
.PHONY : src/engine/Output.o

# target to build an object file
src/engine/Output.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Output.cpp.o
.PHONY : src/engine/Output.cpp.o

src/engine/Output.i: src/engine/Output.cpp.i
.PHONY : src/engine/Output.i

# target to preprocess a source file
src/engine/Output.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Output.cpp.i
.PHONY : src/engine/Output.cpp.i

src/engine/Output.s: src/engine/Output.cpp.s
.PHONY : src/engine/Output.s

# target to generate assembly for a file
src/engine/Output.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Output.cpp.s
.PHONY : src/engine/Output.cpp.s

src/engine/RealtimeCommandQueue.o: src/engine/RealtimeCommandQueue.cpp.o
.PHONY : src/engine/RealtimeCommandQueue.o

# target to build an object file
src/engine/RealtimeCommandQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/RealtimeCommandQueue.cpp.o
.PHONY : src/engine/RealtimeCommandQueue.cpp.o

src/engine/RealtimeCommandQueue.i: src/engine/RealtimeCommandQueue.cpp.i
.PHONY : src/engine/RealtimeCommandQueue.i

# target to preprocess a source file
src/engine/RealtimeCommandQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/RealtimeCommandQueue.cpp.i
.PHONY : src/engine/RealtimeCommandQueue.cpp.i

src/engine/RealtimeCommandQueue.s: src/engine/RealtimeCommandQueue.cpp.s
.PHONY : src/engine/RealtimeCommandQueue.s

# target to generate assembly for a file
src/engine/RealtimeCommandQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/RealtimeCommandQueue.cpp.s
.PHONY : src/engine/RealtimeCommandQueue.cpp.s

src/engine/Sound.o: src/engine/Sound.cpp.o
.PHONY : src/engine/Sound.o

# target to build an object file
src/engine/Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Sound.cpp.o
.PHONY : src/engine/Sound.cpp.o

src/engine/Sound.i: src/engine/Sound.cpp.i
.PHONY : src/engine/Sound.i

# target to preprocess a source file
src/engine/Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Sound.cpp.i
.PHONY : src/engine/Sound.cpp.i

src/engine/Sound.s: src/engine/Sound.cpp.s
.PHONY : src/engine/Sound.s

# target to generate assembly for a file
src/engine/Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Sound.cpp.s
.PHONY : src/engine/Sound.cpp.s

src/engine/Synthesizer.o: src/engine/Synthesizer.cpp.o
.PHONY : src/engine/Synthesizer.o

# target to build an object file
src/engine/Synthesizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Synthesizer.cpp.o
.PHONY : src/engine/Synthesizer.cpp.o

src/engine/Synthesizer.i: src/engine/Synthesizer.cpp.i
.PHONY : src/engine/Synthesizer.i

# target to preprocess a source file
src/engine/Synthesizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Synthesizer.cpp.i
.PHONY : src/engine/Synthesizer.cpp.i

src/engine/Synthesizer.s: src/engine/Synthesizer.cpp.s
.PHONY : src/engine/Synthesizer.s

# target to generate assembly for a file
src/engine/Synthesizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/Synthesizer.cpp.s
.PHONY : src/engine/Synthesizer.cpp.s

src/engine/SynthesizerPatches.o: src/engine/SynthesizerPatches.cpp.o
.PHONY : src/engine/SynthesizerPatches.o

# target to build an object file
src/engine/SynthesizerPatches.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/SynthesizerPatches.cpp.o
.PHONY : src/engine/SynthesizerPatches.cpp.o

src/engine/SynthesizerPatches.i: src/engine/SynthesizerPatches.cpp.i
.PHONY : src/engine/SynthesizerPatches.i

# target to preprocess a source file
src/engine/SynthesizerPatches.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/SynthesizerPatches.cpp.i
.PHONY : src/engine/SynthesizerPatches.cpp.i

src/engine/SynthesizerPatches.s: src/engine/SynthesizerPatches.cpp.s
.PHONY : src/engine/SynthesizerPatches.s

# target to generate assembly for a file
src/engine/SynthesizerPatches.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/SynthesizerPatches.cpp.s
.PHONY : src/engine/SynthesizerPatches.cpp.s

src/engine/TempoEngine.o: src/engine/TempoEngine.cpp.o
.PHONY : src/engine/TempoEngine.o

# target to build an object file
src/engine/TempoEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/TempoEngine.cpp.o
.PHONY : src/engine/TempoEngine.cpp.o

src/engine/TempoEngine.i: src/engine/TempoEngine.cpp.i
.PHONY : src/engine/TempoEngine.i

# target to preprocess a source file
src/engine/TempoEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/TempoEngine.cpp.i
.PHONY : src/engine/TempoEngine.cpp.i

src/engine/TempoEngine.s: src/engine/TempoEngine.cpp.s
.PHONY : src/engine/TempoEngine.s

# target to generate assembly for a file
src/engine/TempoEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/engine/TempoEngine.cpp.s
.PHONY : src/engine/TempoEngine.cpp.s

src/metronome/BuiltInKits.o: src/metronome/BuiltInKits.cpp.o
.PHONY : src/metronome/BuiltInKits.o

# target to build an object file
src/metronome/BuiltInKits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/metronome/BuiltInKits.cpp.o
.PHONY : src/metronome/BuiltInKits.cpp.o

src/metronome/BuiltInKits.i: src/metronome/BuiltInKits.cpp.i
.PHONY : src/metronome/BuiltInKits.i

# target to preprocess a source file
src/metronome/BuiltInKits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/metronome/BuiltInKits.cpp.i
.PHONY : src/metronome/BuiltInKits.cpp.i

src/metronome/BuiltInKits.s: src/metronome/BuiltInKits.cpp.s
.PHONY : src/metronome/BuiltInKits.s

# target to generate assembly for a file
src/metronome/BuiltInKits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/metronome/BuiltInKits.cpp.s
.PHONY : src/metronome/BuiltInKits.cpp.s

src/metronome/Metronome.o: src/metronome/Metronome.cpp.o
.PHONY : src/metronome/Metronome.o

# target to build an object file
src/metronome/Metronome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/metronome/Metronome.cpp.o
.PHONY : src/metronome/Metronome.cpp.o

src/metronome/Metronome.i: src/metronome/Metronome.cpp.i
.PHONY : src/metronome/Metronome.i

# target to preprocess a source file
src/metronome/Metronome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/metronome/Metronome.cpp.i
.PHONY : src/metronome/Metronome.cpp.i

src/metronome/Metronome.s: src/metronome/Metronome.cpp.s
.PHONY : src/metronome/Metronome.s

# target to generate assembly for a file
src/metronome/Metronome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/metronome/Metronome.cpp.s
.PHONY : src/metronome/Metronome.cpp.s

src/scheduler/Scheduler.o: src/scheduler/Scheduler.cpp.o
.PHONY : src/scheduler/Scheduler.o

# target to build an object file
src/scheduler/Scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/scheduler/Scheduler.cpp.o
.PHONY : src/scheduler/Scheduler.cpp.o

src/scheduler/Scheduler.i: src/scheduler/Scheduler.cpp.i
.PHONY : src/scheduler/Scheduler.i

# target to preprocess a source file
src/scheduler/Scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/scheduler/Scheduler.cpp.i
.PHONY : src/scheduler/Scheduler.cpp.i

src/scheduler/Scheduler.s: src/scheduler/Scheduler.cpp.s
.PHONY : src/scheduler/Scheduler.s

# target to generate assembly for a file
src/scheduler/Scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mighty-core.dir/build.make CMakeFiles/mighty-core.dir/src/scheduler/Scheduler.cpp.s
.PHONY : src/scheduler/Scheduler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... DaisySP"
	@echo "... glfw"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... imgui_lib"
	@echo "... mighty-core"
	@echo "... mighty-core-host-check"
	@echo "... mighty-core-synth-host"
	@echo "... mighty-core-ui"
	@echo "... mmc-tests"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_glfw.s"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.o"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.i"
	@echo "... _deps/imgui-src/backends/imgui_impl_opengl3.s"
	@echo "... _deps/imgui-src/imgui.o"
	@echo "... _deps/imgui-src/imgui.i"
	@echo "... _deps/imgui-src/imgui.s"
	@echo "... _deps/imgui-src/imgui_draw.o"
	@echo "... _deps/imgui-src/imgui_draw.i"
	@echo "... _deps/imgui-src/imgui_draw.s"
	@echo "... _deps/imgui-src/imgui_tables.o"
	@echo "... _deps/imgui-src/imgui_tables.i"
	@echo "... _deps/imgui-src/imgui_tables.s"
	@echo "... _deps/imgui-src/imgui_widgets.o"
	@echo "... _deps/imgui-src/imgui_widgets.i"
	@echo "... _deps/imgui-src/imgui_widgets.s"
	@echo "... host/main.o"
	@echo "... host/main.i"
	@echo "... host/main.s"
	@echo "... host/synth_host.o"
	@echo "... host/synth_host.i"
	@echo "... host/synth_host.s"
	@echo "... host/ui_host.o"
	@echo "... host/ui_host.i"
	@echo "... host/ui_host.s"
	@echo "... host/wav_reader.o"
	@echo "... host/wav_reader.i"
	@echo "... host/wav_reader.s"
	@echo "... src/core/MightyMusicCore.o"
	@echo "... src/core/MightyMusicCore.i"
	@echo "... src/core/MightyMusicCore.s"
	@echo "... src/engine/Input.o"
	@echo "... src/engine/Input.i"
	@echo "... src/engine/Input.s"
	@echo "... src/engine/Output.o"
	@echo "... src/engine/Output.i"
	@echo "... src/engine/Output.s"
	@echo "... src/engine/RealtimeCommandQueue.o"
	@echo "... src/engine/RealtimeCommandQueue.i"
	@echo "... src/engine/RealtimeCommandQueue.s"
	@echo "... src/engine/Sound.o"
	@echo "... src/engine/Sound.i"
	@echo "... src/engine/Sound.s"
	@echo "... src/engine/Synthesizer.o"
	@echo "... src/engine/Synthesizer.i"
	@echo "... src/engine/Synthesizer.s"
	@echo "... src/engine/SynthesizerPatches.o"
	@echo "... src/engine/SynthesizerPatches.i"
	@echo "... src/engine/SynthesizerPatches.s"
	@echo "... src/engine/TempoEngine.o"
	@echo "... src/engine/TempoEngine.i"
	@echo "... src/engine/TempoEngine.s"
	@echo "... src/metronome/BuiltInKits.o"
	@echo "... src/metronome/BuiltInKits.i"
	@echo "... src/metronome/BuiltInKits.s"
	@echo "... src/metronome/Metronome.o"
	@echo "... src/metronome/Metronome.i"
	@echo "... src/metronome/Metronome.s"
	@echo "... src/scheduler/Scheduler.o"
	@echo "... src/scheduler/Scheduler.i"
	@echo "... src/scheduler/Scheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

